In [1]:
import datadotworld as dw
ds = dw.load_dataset('makeovermonday/2020w17-weekly-road-fuel-prices', auto_update=True)

In [3]:
ds.dataframes

LazyLoadedDict({'2012': LazyLoadedValue(<pandas.DataFrame>), '2013': LazyLoadedValue(<pandas.DataFrame>), '2014': LazyLoadedValue(<pandas.DataFrame>), '2015': LazyLoadedValue(<pandas.DataFrame>), '2016': LazyLoadedValue(<pandas.DataFrame>), '2017': LazyLoadedValue(<pandas.DataFrame>), '2018': LazyLoadedValue(<pandas.DataFrame>), '2019': LazyLoadedValue(<pandas.DataFrame>), '2020': LazyLoadedValue(<pandas.DataFrame>), 'all_years': LazyLoadedValue(<pandas.DataFrame>), 'all_years_2': LazyLoadedValue(<pandas.DataFrame>), 'charts': LazyLoadedValue(<pandas.DataFrame>), 'contents': LazyLoadedValue(<pandas.DataFrame>), 'methodology': LazyLoadedValue(<pandas.DataFrame>), 'summary': LazyLoadedValue(<pandas.DataFrame>)})

In [6]:
prices = ds.dataframes['all_years_2']

In [7]:
prices

                        date  uslp_pence_per_litre  usld_pence_per_litre
0                     6/9/03             74.590284             76.773394
1                    6/16/03             74.469143             76.689054
2                    6/23/03             74.423566             76.620546
3                    6/30/03             74.352421             76.505260
4                     7/7/03             74.283737             76.457376
5                    7/14/03             74.206577             76.408120
6                    7/21/03             75.065240             76.899144
7                    7/28/03             75.100855             76.861864
8                     8/4/03             75.124384             76.812342
9                    8/11/03             75.444516             77.080738
10                   8/18/03             75.808948             77.438590
11                   8/26/03             76.053011             77.675094
12                    9/1/03             76.125860             77.587704
13                    9/8/03             76.226190             77.670140
14                   9/15/03             76.196425             77.626436
15                   9/22/03             76.148709             77.545842
16                   9/29/03             76.083990             77.526894
17                   10/6/03             76.432933             77.661236
18                  10/13/03             75.897528             77.426488
19                  10/20/03             76.048060             77.544714
20                  10/27/03             75.995460             77.510978
21                   11/3/03             75.996259             77.519974
22                  11/10/03             75.942830             77.469868
23                  11/17/03             75.926843             77.517624
24                  11/24/03             76.015098             77.670648
25                   12/1/03             75.995276             77.657072
26                   12/8/03             75.970566             77.628804
27                  12/15/03             75.959063             77.619338
28                  12/22/03             75.922636             77.613818
29                  12/29/03             75.939699             77.600882
..                       ...                   ...                   ...
852                  10/7/19            126.869495            131.820803
853                 10/14/19            126.906491            131.892908
854                 10/21/19            126.402420            131.279253
855                 10/28/19            125.765514            130.603532
856                  11/4/19            125.558701            130.376095
857                 11/11/19            125.593999            130.424910
858                 11/18/19            125.582346            130.345595
859                 11/25/19            125.319798            130.078313
860                  12/2/19            124.808783            129.793833
861                  12/9/19            124.748176            129.790185
862                 12/16/19            124.329970            129.561762
863                 12/23/19            124.157540            129.811132
864                 12/30/19            124.962151            130.542046
865                   1/6/20            126.085869            131.555157
866                  1/13/20            127.167392            132.688235
867                  1/20/20            127.177227            132.739754
868                  1/27/20            127.334589            132.880881
869                   2/3/20            125.848087            131.475672
870                  2/10/20            124.729360            129.704447
871                  2/17/20            123.796075            128.202849
872                  2/24/20            123.446449            127.674426
873                   3/2/20            122.431272            126.622464
874                   3/9/20            122.243981            126.252648
875                  3/16/20            120.328169            124.363474
876                  3/23/20            119.644504            123.409485
877                  3/30/20            112.452709            118.597998
878                   4/6/20            110.234797            116.833354
879                  4/13/20            109.265819            116.150812
880                  4/20/20            108.632747            115.732573
881  Return to Contents page                   NaN                   NaN

[882 rows x 3 columns]

What is pence per litre?